name: zClans
main: org.bitbucket.zenith4183.zclans.zClans
version: ${project.version}
softdepend: [VanishNoPacket, Permissions, PermissionsBukkit, Vault, PermissionsEx]
permissions:
  zclans.admin.permissions:
    description: Can grant clans permissions
  zclans.admin.reload:
    description: Can reload configuration
  zclans.admin.all-seeing-eye:
    description: Can see all clan chats
  zclans.mod.verify:
    description: Can verify zclans
  zclans.mod.ban:
    description: Can ban players from the entire plugin
  zclans.mod.disband:
    description: Can disband any clan
  zclans.mod.globalff:
    description: Can turn off global friendly fire protection
  zclans.mod.nohide:
    description: Messages from these players cannot be hidden via chat commands
  zclans.mod.home:
    description: Can set other clan's home
  zclans.mod.hometp:
    description: Can teleport to all clans homes
  zclans.mod.bypass:
    description: Can bypass restrictions
  zclans.anyone.list:
    description: Can list zclans
  zclans.anyone.profile:
    description: Can view a clan's profile
  zclans.anyone.roster:
    description: Can veiw a clan's member list
  zclans.anyone.lookup:
    description: Can lookup a player's info
  zclans.anyone.leaderboard:
    description: Can view the leaderboard
  zclans.anyone.alliances:
    description: Can view alliances by clan
  zclans.anyone.rivalries:
    description: Can view rivalries by clan
  zclans.member.profile:
    description: Can view his own clan's profile
  zclans.member.roster:
    description: Can view his own clan's member list
  zclans.member.lookup:
    description: Can view his own player info
  zclans.member.vitals:
    description: Can view his clan's vitals
  zclans.member.coords:
    description: Can view his clan's coords
  zclans.member.stats:
    description: Can view his zclans stats
  zclans.member.bb:
    description: Can view his clan's bulletin board
  zclans.member.bb-add:
    description: Can add to his clan's bulletin board
  zclans.member.bb-toggle:
    description: Can toggle bb on/off
  zclans.member.ff:
    description: Can toggle his own friendly fire
  zclans.member.resign:
    description: Can resign from his clan
  zclans.member.ally:
    description: Can use ally chat
  zclans.member.can-join:
    description: Can join clans
  zclans.member.home:
    description: Can tp to home base
  zclans.leader.create:
    description: Can create zclans
  zclans.leader.home-set:
    description: Can set home base
  zclans.leader.home-regroup:
    description: Can tp entire clan to homebase
  zclans.leader.ally:
    description: Can ally his clan with other zclans
  zclans.leader.rival:
    description: Can start a rivalry with another clan
  zclans.leader.modtag:
    description: Can modify his clan's tag
  zclans.member.kills:
    description: Can view his and other's kills
  zclans.member.tag-toggle:
    description: Can hide his own clan tag
  zclans.mod.mostkilled:
    description: Can view his and other's clans mostkilled
  zclans.mod.keep-items:
    description: Can keep items when teleporting home
  zclans.mod.place:
    description: Can manually place players in clans
  zclans.leader.invite:
    description: Can invite players into his clan
  zclans.leader.kick:
    description: Can kick players form his tea,
  zclans.leader.promote:
    description: Can promote players to clan leaders
  zclans.leader.promotable:
    description: Can be promoted to clan leader
  zclans.leader.demote:
    description: Can demote clan leaders to normal players
  zclans.leader.ff:
    description: Can toggle his clan's friendly fire
  zclans.leader.disband:
    description: Can disband his own clan
  zclans.leader.settrust:
    description: Can set trust levels for members
  zclans.leader.setrank:
    description: Can set ranks
  zclans.admin.*:
    description: Permissions for admins
    default: op
    children:
      zclans.admin.reload: true
      zclans.admin.all-seeing-eye: true
  zclans.mod.*:
    description: Permissions for moderators
    default: op
    children:
      zclans.mod.verify: true
      zclans.mod.ban: true
      zclans.mod.disband: true
      zclans.mod.globalff: true
      zclans.mod.bypass: true
      zclans.mod.home: true
      zclans.mod.mostkilled: true
      zclans.mod.keep-items: true
      zclans.mod.place: true
  zclans.anyone.*:
    description: Permissions for anyone
    default: false
    children:
      zclans.anyone.list: true
      zclans.anyone.profile: true
      zclans.anyone.roster: true
      zclans.anyone.lookup: true
      zclans.anyone.leaderboard: true
      zclans.anyone.alliances: true
      zclans.anyone.rivalries: true
  zclans.member.*:
    description: Permissions for those who can be clan members
    default: false
    children:
      zclans.member.can-join: true
      zclans.member.profile: true
      zclans.member.roster: true
      zclans.member.lookup: true
      zclans.member.vitals: true
      zclans.member.coords: true
      zclans.member.stats: true
      zclans.member.bb: true
      zclans.member.bb-add: true
      zclans.member.bb-toggle: true
      zclans.member.tag-toggle: true
      zclans.member.ff: true
      zclans.member.resign: true
      zclans.member.ally: true
      zclans.member.home: true
      zclans.member.kills: true
  zclans.leader.*:
    description: Permissions for those who can be clan leaders
    default: false
    children:
      zclans.leader.create: true
      zclans.leader.ally: true
      zclans.leader.rival: true
      zclans.leader.modtag: true
      zclans.leader.invite: true
      zclans.leader.kick: true
      zclans.leader.promote: true
      zclans.leader.promotable: true
      zclans.leader.demote: true
      zclans.leader.ff: true
      zclans.leader.disband: true
      zclans.leader.settrust: true
      zclans.leader.home-set: true
      zclans.leader.home-regroup: true
      zclans.leader.setrank: true
